/*
 * DeviGet: Santiago Lopez
 *
 * MineSweeper Challenge
 *
 * API version: API: V1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type MarkRequest struct {
	Column int32 `json:"column,omitempty"`
	Row int32 `json:"row,omitempty"`
}
