/*
 * DeviGet: Santiago Lopez
 *
 * MineSweeper Challenge
 *
 * API version: API: V1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type GridRequest struct {
	Columns int32 `json:"columns,omitempty"`
	Mines int32 `json:"mines,omitempty"`
	Name string `json:"name,omitempty"`
	Rows int32 `json:"rows,omitempty"`
}
