---
swagger: "2.0"
info:
  description: "MineSweeper Challenge"
  version: "API: V1"
  title: "DeviGet: Santiago Lopez"
host: "localhost:8080"
basePath: "/"
tags:
- name: "game-controller"
  description: "Game Controller"
paths:
  /challenge/deviget/minesweeper/v1/game:
    post:
      tags:
      - "game-controller"
      summary: "createGame"
      operationId: "createGameUsingPOST"
      consumes:
      - "application/json"
      produces:
      - "*/*"
      parameters:
      - in: "body"
        name: "request"
        description: "request"
        required: true
        schema:
          $ref: "#/definitions/GridRequest"
        x-exportParamName: "Request"
      responses:
        "200":
          description: "OK"
          schema:
            $ref: "#/definitions/ResponseEntity"
        "201":
          description: "Created"
        "401":
          description: "Unauthorized"
        "403":
          description: "Forbidden"
        "404":
          description: "Not Found"
      deprecated: false
  /challenge/deviget/minesweeper/v1/game/{userName}:
    get:
      tags:
      - "game-controller"
      summary: "getGame"
      operationId: "getGameUsingGET"
      produces:
      - "*/*"
      parameters:
      - name: "userName"
        in: "path"
        description: "userName"
        required: true
        type: "string"
        x-exportParamName: "UserName"
      responses:
        "200":
          description: "OK"
          schema:
            $ref: "#/definitions/ResponseEntity"
        "401":
          description: "Unauthorized"
        "403":
          description: "Forbidden"
        "404":
          description: "Not Found"
      deprecated: false
  /challenge/deviget/minesweeper/v1/game/{userName}/mark/{markType}:
    put:
      tags:
      - "game-controller"
      summary: "setMark"
      operationId: "setMarkUsingPUT"
      consumes:
      - "application/json"
      produces:
      - "*/*"
      parameters:
      - name: "markType"
        in: "path"
        description: "markType"
        required: true
        type: "string"
        x-exportParamName: "MarkType"
      - in: "body"
        name: "request"
        description: "request"
        required: true
        schema:
          $ref: "#/definitions/MarkRequest"
        x-exportParamName: "Request"
      - name: "userName"
        in: "path"
        description: "userName"
        required: true
        type: "string"
        x-exportParamName: "UserName"
      responses:
        "200":
          description: "OK"
          schema:
            $ref: "#/definitions/ResponseEntity"
        "201":
          description: "Created"
        "401":
          description: "Unauthorized"
        "403":
          description: "Forbidden"
        "404":
          description: "Not Found"
      deprecated: false
  /challenge/deviget/minesweeper/v1/game/{userName}/step:
    put:
      tags:
      - "game-controller"
      summary: "stepOn"
      operationId: "stepOnUsingPUT"
      consumes:
      - "application/json"
      produces:
      - "*/*"
      parameters:
      - in: "body"
        name: "request"
        description: "request"
        required: true
        schema:
          $ref: "#/definitions/StepRequest"
        x-exportParamName: "Request"
      - name: "userName"
        in: "path"
        description: "userName"
        required: true
        type: "string"
        x-exportParamName: "UserName"
      responses:
        "200":
          description: "OK"
          schema:
            $ref: "#/definitions/ResponseEntity"
        "201":
          description: "Created"
        "401":
          description: "Unauthorized"
        "403":
          description: "Forbidden"
        "404":
          description: "Not Found"
      deprecated: false
  /challenge/deviget/minesweeper/v1/game/{userName}/timetracker:
    get:
      tags:
      - "game-controller"
      summary: "getTimeTracker"
      operationId: "getTimeTrackerUsingGET"
      produces:
      - "*/*"
      parameters:
      - name: "userName"
        in: "path"
        description: "userName"
        required: true
        type: "string"
        x-exportParamName: "UserName"
      responses:
        "200":
          description: "OK"
          schema:
            $ref: "#/definitions/ResponseEntity"
        "401":
          description: "Unauthorized"
        "403":
          description: "Forbidden"
        "404":
          description: "Not Found"
      deprecated: false
definitions:
  GridRequest:
    type: "object"
    properties:
      columns:
        type: "integer"
        format: "int32"
      mines:
        type: "integer"
        format: "int32"
      name:
        type: "string"
      rows:
        type: "integer"
        format: "int32"
    title: "GridRequest"
    example:
      mines: 6
      columns: 0
      name: "name"
      rows: 1
  MarkRequest:
    type: "object"
    properties:
      column:
        type: "integer"
        format: "int32"
      row:
        type: "integer"
        format: "int32"
    title: "MarkRequest"
    example:
      column: 0
      row: 6
  ResponseEntity:
    type: "object"
    properties:
      body:
        type: "object"
        properties: {}
      statusCode:
        type: "string"
        enum:
        - "100 CONTINUE"
        - "101 SWITCHING_PROTOCOLS"
        - "102 PROCESSING"
        - "103 CHECKPOINT"
        - "200 OK"
        - "201 CREATED"
        - "202 ACCEPTED"
        - "203 NON_AUTHORITATIVE_INFORMATION"
        - "204 NO_CONTENT"
        - "205 RESET_CONTENT"
        - "206 PARTIAL_CONTENT"
        - "207 MULTI_STATUS"
        - "208 ALREADY_REPORTED"
        - "226 IM_USED"
        - "300 MULTIPLE_CHOICES"
        - "301 MOVED_PERMANENTLY"
        - "302 FOUND"
        - "302 MOVED_TEMPORARILY"
        - "303 SEE_OTHER"
        - "304 NOT_MODIFIED"
        - "305 USE_PROXY"
        - "307 TEMPORARY_REDIRECT"
        - "308 PERMANENT_REDIRECT"
        - "400 BAD_REQUEST"
        - "401 UNAUTHORIZED"
        - "402 PAYMENT_REQUIRED"
        - "403 FORBIDDEN"
        - "404 NOT_FOUND"
        - "405 METHOD_NOT_ALLOWED"
        - "406 NOT_ACCEPTABLE"
        - "407 PROXY_AUTHENTICATION_REQUIRED"
        - "408 REQUEST_TIMEOUT"
        - "409 CONFLICT"
        - "410 GONE"
        - "411 LENGTH_REQUIRED"
        - "412 PRECONDITION_FAILED"
        - "413 PAYLOAD_TOO_LARGE"
        - "413 REQUEST_ENTITY_TOO_LARGE"
        - "414 URI_TOO_LONG"
        - "414 REQUEST_URI_TOO_LONG"
        - "415 UNSUPPORTED_MEDIA_TYPE"
        - "416 REQUESTED_RANGE_NOT_SATISFIABLE"
        - "417 EXPECTATION_FAILED"
        - "418 I_AM_A_TEAPOT"
        - "419 INSUFFICIENT_SPACE_ON_RESOURCE"
        - "420 METHOD_FAILURE"
        - "421 DESTINATION_LOCKED"
        - "422 UNPROCESSABLE_ENTITY"
        - "423 LOCKED"
        - "424 FAILED_DEPENDENCY"
        - "425 TOO_EARLY"
        - "426 UPGRADE_REQUIRED"
        - "428 PRECONDITION_REQUIRED"
        - "429 TOO_MANY_REQUESTS"
        - "431 REQUEST_HEADER_FIELDS_TOO_LARGE"
        - "451 UNAVAILABLE_FOR_LEGAL_REASONS"
        - "500 INTERNAL_SERVER_ERROR"
        - "501 NOT_IMPLEMENTED"
        - "502 BAD_GATEWAY"
        - "503 SERVICE_UNAVAILABLE"
        - "504 GATEWAY_TIMEOUT"
        - "505 HTTP_VERSION_NOT_SUPPORTED"
        - "506 VARIANT_ALSO_NEGOTIATES"
        - "507 INSUFFICIENT_STORAGE"
        - "508 LOOP_DETECTED"
        - "509 BANDWIDTH_LIMIT_EXCEEDED"
        - "510 NOT_EXTENDED"
        - "511 NETWORK_AUTHENTICATION_REQUIRED"
      statusCodeValue:
        type: "integer"
        format: "int32"
    title: "ResponseEntity"
  StepRequest:
    type: "object"
    properties:
      column:
        type: "integer"
        format: "int32"
      row:
        type: "integer"
        format: "int32"
    title: "StepRequest"
    example:
      column: 0
      row: 6
